# Ansible playbook - bastion_playbook.yml
---
- hosts: all
  become: yes
  tasks:
    - name: Update all packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600

    - name: Install necessary packages
      apt:
        name: ['package1', 'package2', 'package3']
        state: present
